(function($) {
    $(document).ready(function() {
	
	$('#cholera_gideon_plot_allyears').scianimator({
	    'images': ['images/cholera_gideon_plot_allyears1.png', 'images/cholera_gideon_plot_allyears2.png', 'images/cholera_gideon_plot_allyears3.png', 'images/cholera_gideon_plot_allyears4.png', 'images/cholera_gideon_plot_allyears5.png', 'images/cholera_gideon_plot_allyears6.png', 'images/cholera_gideon_plot_allyears7.png', 'images/cholera_gideon_plot_allyears8.png', 'images/cholera_gideon_plot_allyears9.png', 'images/cholera_gideon_plot_allyears10.png', 'images/cholera_gideon_plot_allyears11.png', 'images/cholera_gideon_plot_allyears12.png', 'images/cholera_gideon_plot_allyears13.png', 'images/cholera_gideon_plot_allyears14.png', 'images/cholera_gideon_plot_allyears15.png', 'images/cholera_gideon_plot_allyears16.png', 'images/cholera_gideon_plot_allyears17.png', 'images/cholera_gideon_plot_allyears18.png', 'images/cholera_gideon_plot_allyears19.png', 'images/cholera_gideon_plot_allyears20.png', 'images/cholera_gideon_plot_allyears21.png', 'images/cholera_gideon_plot_allyears22.png', 'images/cholera_gideon_plot_allyears23.png', 'images/cholera_gideon_plot_allyears24.png', 'images/cholera_gideon_plot_allyears25.png', 'images/cholera_gideon_plot_allyears26.png', 'images/cholera_gideon_plot_allyears27.png', 'images/cholera_gideon_plot_allyears28.png', 'images/cholera_gideon_plot_allyears29.png', 'images/cholera_gideon_plot_allyears30.png', 'images/cholera_gideon_plot_allyears31.png', 'images/cholera_gideon_plot_allyears32.png', 'images/cholera_gideon_plot_allyears33.png', 'images/cholera_gideon_plot_allyears34.png', 'images/cholera_gideon_plot_allyears35.png', 'images/cholera_gideon_plot_allyears36.png', 'images/cholera_gideon_plot_allyears37.png', 'images/cholera_gideon_plot_allyears38.png', 'images/cholera_gideon_plot_allyears39.png', 'images/cholera_gideon_plot_allyears40.png', 'images/cholera_gideon_plot_allyears41.png', 'images/cholera_gideon_plot_allyears42.png', 'images/cholera_gideon_plot_allyears43.png', 'images/cholera_gideon_plot_allyears44.png', 'images/cholera_gideon_plot_allyears45.png', 'images/cholera_gideon_plot_allyears46.png', 'images/cholera_gideon_plot_allyears47.png', 'images/cholera_gideon_plot_allyears48.png', 'images/cholera_gideon_plot_allyears49.png', 'images/cholera_gideon_plot_allyears50.png', 'images/cholera_gideon_plot_allyears51.png', 'images/cholera_gideon_plot_allyears52.png', 'images/cholera_gideon_plot_allyears53.png', 'images/cholera_gideon_plot_allyears54.png', 'images/cholera_gideon_plot_allyears55.png', 'images/cholera_gideon_plot_allyears56.png', 'images/cholera_gideon_plot_allyears57.png', 'images/cholera_gideon_plot_allyears58.png', 'images/cholera_gideon_plot_allyears59.png', 'images/cholera_gideon_plot_allyears60.png', 'images/cholera_gideon_plot_allyears61.png', 'images/cholera_gideon_plot_allyears62.png', 'images/cholera_gideon_plot_allyears63.png', 'images/cholera_gideon_plot_allyears64.png'],
	    'width': 650,
	    'delay': 1000,
	    'loopMode': 'loop',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed'], 'delayMin': 0
	});
	$('#cholera_gideon_plot_allyears').scianimator('play');
    });
})(jQuery);
